# Generated by Django 3.2.25 on 2024-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0008_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
