# Generated by Django 3.2.25 on 2024-11-25 05:45

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0009_alter_course_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='ff0000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
