# Generated by Django 3.2.25 on 2024-11-25 22:19

from django.db import migrations, models
import mt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0010_auto_20241125_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_from',
            field=models.TimeField(null=True, validators=[mt.validators.validate_time_from]),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_to',
            field=models.TimeField(null=True, validators=[mt.validators.validate_time_to]),
        ),
    ]
